name : My first workflow 
  
on : push 

jobs :  
    first_job :
        runs-on : ubuntu-latest 
        steps:
            - name : checkout 
              uses: actions/checkout@v4

            - name :  list and read file 
              run: |
                   echo "My first github "
                   ls -ltra 
                   cat README.md
                   # - name : list files 
            - name : Generate ASCI 
              run : cowsay -f dragon "Run for cover , iam dragon "
             #  run : ls 

            #- name : Read file 
             # run: cat README.md  