name : generate ASCII 
  
on : push 

jobs :  
    ascii_job :
        runs-on : ubuntu-latest 
        steps:
            - name : checkout  Repo 
              uses: actions/checkout@v4

            - name: Execute the shell script 
              run: ./ascii-script.sh
           
              
            - name: List repo files
              run : ls -ltra 