name : generate ASCII 
  
on : push 

jobs :  
    build_job_1:
        
        runs-on : ubuntu-latest 
        steps:
            - name : Install cowsay program 
              run :  sudo apt install cowsay -y

            - name: List repo files
              run : cowsay -f dragon "Run for cover , iam dragon " >> dragon.txt   

            - name: upload the dragon text file 
              uses: actions/upload-artifact@v4
              with:
                    name: dragon-txt-file 
                    path: dragon.txt 
                
    test_job_2: 
        needs: build_job_1
        runs-on : ubuntu-latest    
        steps: 
        - name : Download Dragon txt 
          uses: actions/download-artifact@v4
          with:
              name: dragon-txt-file 
        - name: Test File Existes 
          run: grep -i "dragon" dragon.txt 
    deploy_job_3:
            runs-on : ubuntu-latest
            needs : test_job_2
            steps:
                - name : Download Dragon txt 
                  uses: actions/download-artifact@v4
                  with:
                    name: dragon-txt-file 

                - name : Read file 
                  run :  cat dragon.txt
    
                - name: deploy 
                  run : echo Deploying ..........
       
          
           
              
          