name: Docker Build and Deploy

on:
  push

env:
 # DOCKER_IMAGE_NAME: my-docker-image
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE_NAME: github-action.nginx 
  DEPLOY_ENV: production  # Environment to deploy to (e.g., staging, production)

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo  docker login --username=$vars.DOCKER_USERNAME }}" --password=${{secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_REGISTRY }}/${{vars.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest 

      - name: Push Docker image
        run: docker push ${{ env.DOCKER_REGISTRY }}/${{vars.vars.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-docker  # Ensure this job runs after the Docker build job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Docker container
        run: |
          docker run -d \
            --name my-container \
            ${{ env.DOCKER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest